version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
      - logger
      - rabbitmq
    networks:
      - postgres_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e-commerce
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres_network

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - logger
    networks:
      - postgres_network

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq
      - logger
    networks:
      - postgres_network
    
  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - rabbitmq
      - logger
    networks:
      - postgres_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - postgres_network

  logger:
    container_name: logger
    build:
      context: ./logger
    ports:
      - "8084:8084"
    depends_on:
      - elasticsearch
      - rabbitmq
      - grafana
    networks:
      - postgres_network
  
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    networks:
      - postgres_network
    
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres:
